#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")


env.add_source_files(env.modules_sources, "*.cpp")
env.add_source_files(env.modules_sources, "core/*.cpp")
env.add_source_files(env.modules_sources, "resources/*.cpp")
env.add_source_files(env.modules_sources, "scene/*.cpp")
if env.editor_build:
    env.add_source_files(env.modules_sources, "editor/*.cpp")
    SConscript("editor/script_templates/SCsub")
